/**
 * Git Sync Module
 * 
 * Handles synchronization of dashboard state via Git.
 * Enables cross-machine migration and state backup.
 */

const { execSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

/**
 * GitSync class for managing state synchronization
 */
class GitSync {
  /**
   * @param {Object} options
   * @param {string} options.stateDir - Directory containing state files
   * @param {Object} options.config - Sync configuration
   * @param {string} options.config.remote - Git remote name (default: 'origin')
   * @param {string} options.config.branch - Git branch (default: 'main')
   * @param {boolean} options.config.autoCommit - Auto-commit changes
   */
  constructor(options) {
    this.stateDir = path.resolve(options.stateDir);
    this.config = {
      remote: options.config?.remote || 'origin',
      branch: options.config?.branch || 'main',
      autoCommit: options.config?.autoCommit !== false
    };
    this.syncInProgress = false;
  }

  /**
   * Check if directory is a git repository
   * @returns {boolean}
   */
  isGitRepo() {
    const gitDir = path.join(this.stateDir, '.git');
    return fs.existsSync(gitDir);
  }

  /**
   * Execute a git command
   * @param {string[]} args - Git arguments
   * @param {Object} options - Execution options
   * @returns {string} - Command output
   */
  git(args, options = {}) {
    const defaultOptions = {
      cwd: this.stateDir,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe']
    };
    
    try {
      return execSync(`git ${args.join(' ')}`, { ...defaultOptions, ...options });
    } catch (error) {
      if (options.allowFailure) {
        return error.stderr?.toString() || '';
      }
      throw error;
    }
  }

  /**
   * Initialize git repository
   * @param {string} [remoteUrl] - Optional remote URL to add
   * @returns {{ success: boolean, message: string }}
   */
  init(remoteUrl) {
    try {
      if (!this.isGitRepo()) {
        this.git(['init']);
        console.log('[GitSync] Initialized git repository');
      }
      
      if (remoteUrl) {
        // Check if remote already exists
        const remotes = this.git(['remote'], { allowFailure: true });
        if (!remotes.includes(this.config.remote)) {
          this.git(['remote', 'add', this.config.remote, remoteUrl]);
          console.log(`[GitSync] Added remote: ${remoteUrl}`);
        } else {
          // Update existing remote
          this.git(['remote', 'set-url', this.config.remote, remoteUrl]);
          console.log(`[GitSync] Updated remote: ${remoteUrl}`);
        }
      }
      
      // Create .gitignore if it doesn't exist
      const gitignorePath = path.join(this.stateDir, '.gitignore');
      if (!fs.existsSync(gitignorePath)) {
        fs.writeFileSync(gitignorePath, `# Auto-generated by PM Dashboard
*.log
*.tmp
.DS_Store
node_modules/
`);
        console.log('[GitSync] Created .gitignore');
      }
      
      return { success: true, message: 'Git repository initialized' };
    } catch (error) {
      return { success: false, message: error.message };
    }
  }

  /**
   * Get current git status
   * @returns {{ clean: boolean, changes: string[] }}
   */
  getStatus() {
    if (!this.isGitRepo()) {
      return { clean: true, changes: [], initialized: false };
    }
    
    const output = this.git(['status', '--porcelain'], { allowFailure: true });
    const changes = output.trim().split('\n').filter(Boolean);
    
    return {
      clean: changes.length === 0,
      changes,
      initialized: true
    };
  }

  /**
   * Get current commit hash
   * @returns {string|null}
   */
  getCurrentCommit() {
    if (!this.isGitRepo()) return null;
    
    try {
      return this.git(['rev-parse', 'HEAD'], { allowFailure: true }).trim();
    } catch {
      return null;
    }
  }

  /**
   * Check if remote is configured
   * @returns {boolean}
   */
  hasRemote() {
    if (!this.isGitRepo()) return false;
    
    const remotes = this.git(['remote'], { allowFailure: true });
    return remotes.includes(this.config.remote);
  }

  /**
   * Pull changes from remote
   * @returns {{ success: boolean, message: string, hadChanges: boolean }}
   */
  pull() {
    if (!this.isGitRepo()) {
      return { success: false, message: 'Not a git repository', hadChanges: false };
    }
    
    if (!this.hasRemote()) {
      return { success: false, message: 'No remote configured', hadChanges: false };
    }
    
    try {
      const before = this.getCurrentCommit();
      this.git(['pull', this.config.remote, this.config.branch], { allowFailure: true });
      const after = this.getCurrentCommit();
      
      return {
        success: true,
        message: before === after ? 'Already up to date' : 'Pulled new changes',
        hadChanges: before !== after
      };
    } catch (error) {
      // Handle merge conflicts
      if (error.message?.includes('CONFLICT')) {
        return {
          success: false,
          message: 'Merge conflict detected. Manual resolution required.',
          hadChanges: false,
          conflict: true
        };
      }
      return { success: false, message: error.message, hadChanges: false };
    }
  }

  /**
   * Stage and commit all changes
   * @param {string} [message] - Commit message
   * @returns {{ success: boolean, message: string, committed: boolean }}
   */
  commit(message) {
    if (!this.isGitRepo()) {
      return { success: false, message: 'Not a git repository', committed: false };
    }
    
    const status = this.getStatus();
    if (status.clean) {
      return { success: true, message: 'No changes to commit', committed: false };
    }
    
    try {
      // Stage all changes
      this.git(['add', '.']);
      
      // Commit
      const commitMessage = message || `Dashboard sync: ${new Date().toISOString()}`;
      this.git(['commit', '-m', commitMessage]);
      
      return { success: true, message: 'Changes committed', committed: true };
    } catch (error) {
      return { success: false, message: error.message, committed: false };
    }
  }

  /**
   * Push changes to remote
   * @returns {{ success: boolean, message: string }}
   */
  push() {
    if (!this.isGitRepo()) {
      return { success: false, message: 'Not a git repository' };
    }
    
    if (!this.hasRemote()) {
      return { success: false, message: 'No remote configured' };
    }
    
    try {
      this.git(['push', this.config.remote, this.config.branch]);
      return { success: true, message: 'Changes pushed to remote' };
    } catch (error) {
      // Try push with upstream flag
      try {
        this.git(['push', '-u', this.config.remote, this.config.branch]);
        return { success: true, message: 'Changes pushed to remote (new branch)' };
      } catch (upstreamError) {
        return { success: false, message: upstreamError.message };
      }
    }
  }

  /**
   * Perform full sync: pull, commit, push
   * @returns {{ success: boolean, steps: Object[] }}
   */
  async sync() {
    if (this.syncInProgress) {
      return { success: false, message: 'Sync already in progress', steps: [] };
    }
    
    this.syncInProgress = true;
    const steps = [];
    
    try {
      // Step 1: Check repository status
      const status = this.getStatus();
      steps.push({ step: 'status', result: status });
      
      if (!status.initialized) {
        return { success: false, message: 'Not a git repository', steps };
      }
      
      // Step 2: Pull remote changes
      if (this.hasRemote()) {
        const pullResult = this.pull();
        steps.push({ step: 'pull', result: pullResult });
        
        if (!pullResult.success && pullResult.conflict) {
          return { success: false, message: pullResult.message, steps };
        }
      }
      
      // Step 3: Commit local changes
      if (this.config.autoCommit && !status.clean) {
        const commitResult = this.commit();
        steps.push({ step: 'commit', result: commitResult });
        
        if (!commitResult.success) {
          return { success: false, message: commitResult.message, steps };
        }
      }
      
      // Step 4: Push to remote
      if (this.hasRemote()) {
        const pushResult = this.push();
        steps.push({ step: 'push', result: pushResult });
        
        if (!pushResult.success) {
          return { success: false, message: pushResult.message, steps };
        }
      }
      
      return {
        success: true,
        message: 'Sync completed successfully',
        steps,
        commitHash: this.getCurrentCommit()
      };
    } catch (error) {
      return { success: false, message: error.message, steps };
    } finally {
      this.syncInProgress = false;
    }
  }

  /**
   * Clone a remote repository to state directory
   * @param {string} remoteUrl - Remote repository URL
   * @returns {{ success: boolean, message: string }}
   */
  clone(remoteUrl) {
    try {
      // If directory exists but isn't a git repo, we need to handle it
      if (fs.existsSync(this.stateDir)) {
        if (this.isGitRepo()) {
          return { success: false, message: 'Directory already contains a git repository' };
        }
        
        // Directory exists but no git - init and add remote
        return this.init(remoteUrl);
      }
      
      // Clone to parent, rename to stateDir name
      const parentDir = path.dirname(this.stateDir);
      const dirName = path.basename(this.stateDir);
      
      // Ensure parent exists
      if (!fs.existsSync(parentDir)) {
        fs.mkdirSync(parentDir, { recursive: true });
      }
      
      execSync(`git clone ${remoteUrl} ${dirName}`, { cwd: parentDir, encoding: 'utf8' });
      
      return { success: true, message: 'Repository cloned successfully' };
    } catch (error) {
      return { success: false, message: error.message };
    }
  }

  /**
   * Get sync history (last N commits)
   * @param {number} [limit=10] - Number of commits to show
   * @returns {Array}
   */
  getHistory(limit = 10) {
    if (!this.isGitRepo()) return [];
    
    try {
      const output = this.git([
        'log',
        `-${limit}`,
        '--pretty=format:%H|%ci|%s',
        '--'
      ], { allowFailure: true });
      
      return output.trim().split('\n').filter(Boolean).map(line => {
        const [hash, date, message] = line.split('|');
        return { hash, date, message };
      });
    } catch {
      return [];
    }
  }

  /**
   * Check if there are uncommitted changes
   * @returns {boolean}
   */
  hasUncommittedChanges() {
    const status = this.getStatus();
    return !status.clean;
  }

  /**
   * Get remote URL
   * @returns {string|null}
   */
  getRemoteUrl() {
    if (!this.isGitRepo() || !this.hasRemote()) return null;
    
    try {
      return this.git(['remote', 'get-url', this.config.remote], { allowFailure: true }).trim();
    } catch {
      return null;
    }
  }
}

/**
 * Project state file sync (individual JSON files for Git-friendliness)
 */
class ProjectFileSync {
  /**
   * @param {string} projectsDir - Directory for project state files
   */
  constructor(projectsDir) {
    this.projectsDir = projectsDir;
  }

  /**
   * Ensure projects directory exists
   */
  ensureDir() {
    if (!fs.existsSync(this.projectsDir)) {
      fs.mkdirSync(this.projectsDir, { recursive: true });
    }
  }

  /**
   * Save project state to file
   * @param {Object} state - Project state
   */
  saveProject(state) {
    this.ensureDir();
    
    const filePath = path.join(this.projectsDir, `${state.project_name}.json`);
    const content = {
      ...state,
      _metadata: {
        last_modified: new Date().toISOString(),
        version: 1
      }
    };
    
    fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
    console.log(`[ProjectFileSync] Saved: ${state.project_name}`);
  }

  /**
   * Load project state from file
   * @param {string} name - Project name
   * @returns {Object|null}
   */
  loadProject(name) {
    const filePath = path.join(this.projectsDir, `${name}.json`);
    
    if (!fs.existsSync(filePath)) return null;
    
    try {
      return JSON.parse(fs.readFileSync(filePath, 'utf8'));
    } catch (error) {
      console.error(`[ProjectFileSync] Failed to load ${name}:`, error.message);
      return null;
    }
  }

  /**
   * Load all project states
   * @returns {Object[]}
   */
  loadAllProjects() {
    if (!fs.existsSync(this.projectsDir)) return [];
    
    const files = fs.readdirSync(this.projectsDir).filter(f => f.endsWith('.json'));
    
    return files.map(file => {
      try {
        return JSON.parse(fs.readFileSync(path.join(this.projectsDir, file), 'utf8'));
      } catch {
        return null;
      }
    }).filter(Boolean);
  }

  /**
   * Delete project state file
   * @param {string} name - Project name
   */
  deleteProject(name) {
    const filePath = path.join(this.projectsDir, `${name}.json`);
    
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      console.log(`[ProjectFileSync] Deleted: ${name}`);
    }
  }
}

module.exports = {
  GitSync,
  ProjectFileSync
};
